REVOKE CREATE ON SCHEMA public FROM PUBLIC;
REVOKE ALL ON ALL FUNCTIONS IN SCHEMA authz FROM PUBLIC,js_auth,js_social,js_ops,js_publication,js_worker,js_vault,js_vault_auth,js_media,js_media_worker;
REVOKE ALL ON ALL TABLES IN SCHEMA identity,ops,infra,social FROM js_auth,js_social,js_ops,js_publication,js_worker,js_vault,js_vault_auth,js_media,js_media_worker;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA identity,ops,infra,social FROM js_auth,js_social,js_ops,js_publication,js_worker,js_media,js_media_worker;
GRANT USAGE ON SCHEMA identity,social,infra,ops,authz TO js_auth;
GRANT SELECT,INSERT,UPDATE ON identity.principal,identity.account_binding,identity.session TO js_auth;
GRANT SELECT,INSERT,DELETE ON identity.login_flow TO js_auth;
GRANT SELECT ON identity.platform_grant,identity.organization_grant,ops.agency TO js_auth;
GRANT SELECT,INSERT ON social.profile TO js_auth;
GRANT UPDATE(handle,display_name,bio,version) ON social.profile TO js_auth;
GRANT INSERT ON infra.audit_event TO js_auth;
GRANT USAGE ON SCHEMA social,infra,authz TO js_social;
GRANT SELECT,INSERT,UPDATE,DELETE ON social.community_follow,social.post,social.post_revision,social.comment,social.comment_revision,social.post_vote,social.bookmark,social.repost,social.profile_block,social.profile_follow,social.case_follow TO js_social;
GRANT SELECT ON social.community_member TO js_social;
GRANT INSERT(community_id,profile_id,role,state),UPDATE(state,version) ON social.community_member TO js_social;
GRANT SELECT ON social.moderation_case,social.moderation_decision TO js_social;
GRANT INSERT(id,post_id,comment_id,target_version,reporter_ref,reason_code,grounds,state) ON social.moderation_case TO js_social;
GRANT INSERT(id,moderation_case_id,sequence,action,rule_version,actor_ref,reason,author_reason) ON social.moderation_decision TO js_social;
GRANT UPDATE(state,version) ON social.moderation_case TO js_social;
GRANT SELECT ON social.author_moderation_decision,social.appeal,social.appeal_decision TO js_social;
GRANT INSERT(id,decision_id,appellant_ref,grounds,state) ON social.appeal TO js_social;
GRANT UPDATE(state,reviewer_ref,version) ON social.appeal TO js_social;
GRANT INSERT(id,appeal_id,result,author_reason,restoration_state,restoration_reason,reviewer_ref) ON social.appeal_decision TO js_social;
GRANT SELECT ON social.content_report_target TO js_social;
GRANT SELECT ON social.eligible_question_response,social.selected_response TO js_social;
GRANT INSERT(post_id,comment_id,selected_by,post_revision,comment_revision),UPDATE(comment_id,selected_by,post_revision,comment_revision),DELETE ON social.selected_response TO js_social;
GRANT SELECT ON social.community TO js_social;
GRANT UPDATE(id) ON social.community TO js_social;
GRANT SELECT ON social.profile,social.post_stats,social.case_receipt,social.case_receipt_event TO js_social;
GRANT SELECT ON social.notification,social.activity_visible,social.activity_reply_target,social.activity_case_target,social.activity_review_target TO js_social;
GRANT UPDATE(read_at) ON social.notification TO js_social;
GRANT SELECT(profile_id,notification_channels) ON social.feed_preference TO js_social,js_worker;
GRANT SELECT(profile_id,muted_profile_id,muted_community_id,expires_at) ON social.mute TO js_social,js_worker;
GRANT SELECT(version) ON social.feed_preference TO js_social;
GRANT INSERT(profile_id,notification_channels,policy_version,version),UPDATE(notification_channels,policy_version,version) ON social.feed_preference TO js_social;
GRANT SELECT(id,created_at) ON social.mute TO js_social;
GRANT INSERT(id,profile_id,muted_profile_id,muted_community_id,expires_at),UPDATE(expires_at,created_at),DELETE ON social.mute TO js_social;
GRANT EXECUTE ON FUNCTION authz.current_profile() TO js_social;
-- Row locks in social commands need an UPDATE column; actual profile updates stay in auth.
GRANT UPDATE(id) ON social.profile TO js_social;
GRANT USAGE ON SCHEMA ops,social,infra,authz TO js_ops,js_publication;
GRANT SELECT ON social.profile,ops.agency,social.case_receipt,social.case_receipt_event TO js_ops,js_publication;
GRANT SELECT,INSERT ON ops.report TO js_ops;
GRANT UPDATE(id) ON ops.report TO js_ops;
GRANT SELECT,INSERT,UPDATE ON ops.intake_review,ops.case_record,ops.obligation TO js_ops;
GRANT SELECT,INSERT ON ops.case_event,ops.case_observation TO js_ops;
GRANT INSERT ON ops.coordinator_assignment,ops.verification_decision TO js_ops;
GRANT SELECT ON ops.publication_binding TO js_ops;
GRANT SELECT ON ops.publication_status,ops.publication_history TO js_ops,js_publication;
GRANT SELECT(id,publication_preference) ON ops.report TO js_publication;
GRANT SELECT ON ops.case_record,ops.obligation,ops.case_event,ops.case_observation TO js_publication;
GRANT UPDATE(id) ON ops.case_record TO js_publication;
GRANT SELECT,INSERT,UPDATE ON ops.publication_binding TO js_publication;
GRANT INSERT ON ops.publication_decision TO js_publication;
GRANT SELECT,INSERT,UPDATE ON social.case_receipt TO js_publication;
GRANT SELECT,INSERT,DELETE ON social.case_receipt_event TO js_publication;
GRANT SELECT,INSERT,UPDATE ON infra.idempotency_record TO js_social,js_ops,js_publication;
GRANT INSERT ON infra.outbox TO js_social,js_ops,js_publication;
GRANT USAGE ON SCHEMA social,infra TO js_worker;
GRANT SELECT,UPDATE ON infra.outbox TO js_worker;
GRANT SELECT,INSERT ON infra.processed_event TO js_worker;
GRANT SELECT ON social.post TO js_worker;
GRANT SELECT(post_id,value) ON social.post_vote TO js_worker;
GRANT SELECT(id,post_id,state,author_id,parent_id,published_version) ON social.comment TO js_worker;
GRANT SELECT ON social.profile,social.community,social.profile_block,social.case_follow,social.case_receipt,social.activity_reply_target,social.activity_case_target TO js_worker;
GRANT SELECT,INSERT ON social.notification TO js_worker;
GRANT SELECT ON social.activity_review_source TO js_worker;
GRANT SELECT(post_id) ON social.repost TO js_worker;
GRANT UPDATE(id) ON social.post TO js_worker;
GRANT SELECT,INSERT,UPDATE ON social.post_stats TO js_worker;
GRANT USAGE ON SCHEMA authz TO js_vault_auth;
GRANT EXECUTE ON FUNCTION authz.authenticate(bytea,text,text) TO js_vault_auth;
GRANT EXECUTE ON FUNCTION authz.authenticate(bytea,text,text),authz.principal(),authz.has_role(text),authz.agency(uuid),authz.owns_alias(uuid),authz.owns_report(uuid),authz.owns_case(uuid),authz.case_access(uuid),authz.lock_principal(uuid),authz.lock_profile(uuid),authz.owner_tasks(uuid) TO js_auth,js_social,js_ops,js_publication;
GRANT EXECUTE ON FUNCTION authz.media_attachable(uuid,uuid),authz.report_media_ids(uuid),authz.report_ocr_region(uuid,uuid,text) TO js_ops;

GRANT USAGE ON SCHEMA social,infra,authz TO js_media,js_media_worker;
GRANT SELECT,INSERT,UPDATE ON social.media_asset,infra.upload_session,infra.analysis_job,infra.analysis_task TO js_media;
GRANT SELECT,INSERT,UPDATE ON infra.upload_part TO js_media;
GRANT SELECT ON infra.media_derivative TO js_media;
GRANT SELECT,UPDATE ON social.media_asset,infra.upload_session,infra.analysis_job,infra.analysis_task TO js_media_worker;
GRANT SELECT,UPDATE ON infra.upload_part TO js_media_worker;
GRANT SELECT,INSERT,UPDATE ON infra.media_derivative TO js_media_worker;
GRANT SELECT,INSERT ON ops.report_media TO js_ops;
GRANT EXECUTE ON FUNCTION authz.media_read(uuid),authz.media_owner(uuid),authz.analysis_owner(uuid),authz.owns_alias(uuid),authz.media_attached(uuid) TO js_media;
GRANT EXECUTE ON FUNCTION authz.media_job_live(uuid),authz.media_retained(uuid) TO js_media_worker;

-- Resident public-sharing requests use owner RLS and minimal publisher projections.
GRANT SELECT ON ops.publication_withdrawal_request,ops.publication_withdrawal_outcome TO js_ops;
GRANT INSERT(id,report_id,case_id,receipt_id,client_request_id,publication_version,reason_code) ON ops.publication_withdrawal_request TO js_ops;
GRANT EXECUTE ON FUNCTION authz.withdrawal_request_allowed(uuid,uuid,uuid,bigint) TO js_ops;
GRANT SELECT(id,case_id,receipt_id,publication_version,reason_code,state,version,created_at) ON ops.publication_withdrawal_request TO js_publication;
GRANT UPDATE(state,version) ON ops.publication_withdrawal_request TO js_publication;
GRANT INSERT(id,request_id,result,case_version,publication_version,internal_reason,resident_reason,reviewer_ref) ON ops.publication_withdrawal_decision TO js_publication;
GRANT SELECT ON ops.publication_withdrawal_review TO js_publication;
GRANT UPDATE(state,version) ON ops.publication_withdrawal_request TO js_ops;
GRANT INSERT(request_id) ON ops.publication_withdrawal_cancel TO js_ops;
GRANT SELECT ON ops.publication_sharing_eligibility TO js_ops,js_publication;

-- Resident consent never grants direct publication or rewrites report preference.
GRANT SELECT ON ops.publication_sharing_renewal,ops.publication_sharing_renewal_review TO js_ops;
GRANT INSERT(id,request_id,report_id,client_request_id,publication_version) ON ops.publication_sharing_renewal TO js_ops;
GRANT UPDATE(state,version) ON ops.publication_sharing_renewal TO js_ops;
GRANT EXECUTE ON FUNCTION authz.sharing_renewal_target(uuid,uuid,bigint),authz.sharing_renewal_allowed(uuid,uuid,bigint) TO js_ops;
