// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type InfraIdempotencyRecord struct {
	PrincipalRef     uuid.UUID          `json:"principal_ref"`
	Operation        string             `json:"operation"`
	IdempotencyKey   string             `json:"idempotency_key"`
	RequestHash      []byte             `json:"request_hash"`
	ResultResourceID *uuid.UUID         `json:"result_resource_id"`
	ResponseCode     int32              `json:"response_code"`
	ResponseBody     []byte             `json:"response_body"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
}

type InfraOutbox struct {
	ID               uuid.UUID          `json:"id"`
	AggregateType    string             `json:"aggregate_type"`
	AggregateID      uuid.UUID          `json:"aggregate_id"`
	AggregateVersion int64              `json:"aggregate_version"`
	EventType        string             `json:"event_type"`
	PayloadVersion   int32              `json:"payload_version"`
	Payload          []byte             `json:"payload"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	AvailableAt      pgtype.Timestamptz `json:"available_at"`
	LeaseUntil       pgtype.Timestamptz `json:"lease_until"`
	LeaseOwner       pgtype.Text        `json:"lease_owner"`
	LeaseToken       *uuid.UUID         `json:"lease_token"`
	DeliveredAt      pgtype.Timestamptz `json:"delivered_at"`
	DeadLetteredAt   pgtype.Timestamptz `json:"dead_lettered_at"`
	Attempts         int32              `json:"attempts"`
	LastErrorCode    pgtype.Text        `json:"last_error_code"`
}

type OpsCaseEvent struct {
	ID         uuid.UUID          `json:"id"`
	CaseID     uuid.UUID          `json:"case_id"`
	Sequence   int64              `json:"sequence"`
	EventType  string             `json:"event_type"`
	ActorRef   uuid.UUID          `json:"actor_ref"`
	ActorRole  string             `json:"actor_role"`
	Payload    []byte             `json:"payload"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
	RecordedAt pgtype.Timestamptz `json:"recorded_at"`
}

type OpsCaseRecord struct {
	ID                  uuid.UUID          `json:"id"`
	CategoryCode        string             `json:"category_code"`
	State               string             `json:"state"`
	FirstValidReportAt  pgtype.Timestamptz `json:"first_valid_report_at"`
	OperationalLocation interface{}        `json:"operational_location"`
	AccuracyM           pgtype.Int4        `json:"accuracy_m"`
	UrgencyTier         int16              `json:"urgency_tier"`
	UrgencyReviewRef    *uuid.UUID         `json:"urgency_review_ref"`
	Version             int64              `json:"version"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type OpsIntakeReview struct {
	ReportID   uuid.UUID          `json:"report_id"`
	CaseID     *uuid.UUID         `json:"case_id"`
	State      string             `json:"state"`
	Version    int64              `json:"version"`
	ReviewedBy *uuid.UUID         `json:"reviewed_by"`
	ReviewedAt pgtype.Timestamptz `json:"reviewed_at"`
}

type OpsObligation struct {
	ID                     uuid.UUID          `json:"id"`
	CaseID                 uuid.UUID          `json:"case_id"`
	AgencyID               *uuid.UUID         `json:"agency_id"`
	ObligationType         string             `json:"obligation_type"`
	State                  string             `json:"state"`
	AuthorityBasisRef      pgtype.Text        `json:"authority_basis_ref"`
	DueAt                  pgtype.Timestamptz `json:"due_at"`
	AcceptedAt             pgtype.Timestamptz `json:"accepted_at"`
	CompletedAt            pgtype.Timestamptz `json:"completed_at"`
	Version                int64              `json:"version"`
	RequiredForRestoration bool               `json:"required_for_restoration"`
	ParentObligationID     *uuid.UUID         `json:"parent_obligation_id"`
	WorkSummary            string             `json:"work_summary"`
	CompletionActorRef     *uuid.UUID         `json:"completion_actor_ref"`
}

type OpsPublicationBinding struct {
	CaseID              uuid.UUID          `json:"case_id"`
	ReceiptID           uuid.UUID          `json:"receipt_id"`
	ApprovedCaseVersion int64              `json:"approved_case_version"`
	ReviewerRef         uuid.UUID          `json:"reviewer_ref"`
	DecisionRef         string             `json:"decision_ref"`
	ApprovedAt          pgtype.Timestamptz `json:"approved_at"`
}

type OpsReport struct {
	ID                    uuid.UUID          `json:"id"`
	ClientSubmissionID    uuid.UUID          `json:"client_submission_id"`
	ReporterRef           *uuid.UUID         `json:"reporter_ref"`
	SourceChannel         string             `json:"source_channel"`
	LanguageTag           string             `json:"language_tag"`
	Statement             string             `json:"statement"`
	ObservedAt            pgtype.Timestamptz `json:"observed_at"`
	ReceivedAt            pgtype.Timestamptz `json:"received_at"`
	Classification        string             `json:"classification"`
	PublicationPreference string             `json:"publication_preference"`
	IntakeMetadata        []byte             `json:"intake_metadata"`
	RetentionPolicyID     string             `json:"retention_policy_id"`
	RequestHash           []byte             `json:"request_hash"`
	Version               int64              `json:"version"`
}

type SocialActivityVisible struct {
	ID                   uuid.UUID          `json:"id"`
	RecipientID          uuid.UUID          `json:"recipient_id"`
	Kind                 string             `json:"kind"`
	PostID               *uuid.UUID         `json:"post_id"`
	ReceiptID            *uuid.UUID         `json:"receipt_id"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	ReadAt               pgtype.Timestamptz `json:"read_at"`
	ActorID              *uuid.UUID         `json:"actor_id"`
	DisplayName          pgtype.Text        `json:"display_name"`
	Handle               pgtype.Text        `json:"handle"`
	Title                pgtype.Text        `json:"title"`
	ModerationDecisionID *uuid.UUID         `json:"moderation_decision_id"`
	AppealID             *uuid.UUID         `json:"appeal_id"`
	ContentReportID      *uuid.UUID         `json:"content_report_id"`
}

type SocialAppeal struct {
	ID           uuid.UUID          `json:"id"`
	DecisionID   uuid.UUID          `json:"decision_id"`
	AppellantRef uuid.UUID          `json:"appellant_ref"`
	Grounds      string             `json:"grounds"`
	State        string             `json:"state"`
	ReviewerRef  *uuid.UUID         `json:"reviewer_ref"`
	Version      int64              `json:"version"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type SocialAppealDecision struct {
	ID                uuid.UUID          `json:"id"`
	AppealID          uuid.UUID          `json:"appeal_id"`
	Result            string             `json:"result"`
	AuthorReason      string             `json:"author_reason"`
	RestorationState  string             `json:"restoration_state"`
	RestorationReason string             `json:"restoration_reason"`
	ReviewerRef       uuid.UUID          `json:"reviewer_ref"`
	DecidedAt         pgtype.Timestamptz `json:"decided_at"`
}

type SocialAuthorModerationDecision struct {
	ID             uuid.UUID          `json:"id"`
	TargetType     string             `json:"target_type"`
	TargetID       *uuid.UUID         `json:"target_id"`
	PostID         uuid.UUID          `json:"post_id"`
	TargetRevision int64              `json:"target_revision"`
	Action         string             `json:"action"`
	RuleVersion    string             `json:"rule_version"`
	Reason         string             `json:"reason"`
	DecidedAt      pgtype.Timestamptz `json:"decided_at"`
}

type SocialCaseReceipt struct {
	ID                uuid.UUID          `json:"id"`
	Title             string             `json:"title"`
	SafeSummary       string             `json:"safe_summary"`
	AreaLabel         string             `json:"area_label"`
	PublicState       string             `json:"public_state"`
	UrgencyTier       int16              `json:"urgency_tier"`
	FirstReportedAt   pgtype.Timestamptz `json:"first_reported_at"`
	NextUpdateDueAt   pgtype.Timestamptz `json:"next_update_due_at"`
	Responsibilities  []byte             `json:"responsibilities"`
	RankFeatures      []byte             `json:"rank_features"`
	ProjectionVersion int64              `json:"projection_version"`
	PublicationState  string             `json:"publication_state"`
	PublishedAt       pgtype.Timestamptz `json:"published_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	PolicyVersion     string             `json:"policy_version"`
}

type SocialCaseReceiptEvent struct {
	ReceiptID         uuid.UUID          `json:"receipt_id"`
	Sequence          int64              `json:"sequence"`
	Type              string             `json:"type"`
	SafeText          string             `json:"safe_text"`
	ActorType         string             `json:"actor_type"`
	OccurredAt        pgtype.Timestamptz `json:"occurred_at"`
	ProjectionVersion int64              `json:"projection_version"`
}

type SocialComment struct {
	ID               uuid.UUID          `json:"id"`
	PostID           uuid.UUID          `json:"post_id"`
	ParentID         *uuid.UUID         `json:"parent_id"`
	AuthorID         uuid.UUID          `json:"author_id"`
	Body             string             `json:"body"`
	Depth            int16              `json:"depth"`
	State            string             `json:"state"`
	Version          int64              `json:"version"`
	CurrentRevision  int64              `json:"current_revision"`
	PublishedVersion pgtype.Int8        `json:"published_version"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type SocialContentReportTarget struct {
	TargetType   string      `json:"target_type"`
	TargetID     uuid.UUID   `json:"target_id"`
	PostID       uuid.UUID   `json:"post_id"`
	AuthorID     *uuid.UUID  `json:"author_id"`
	PostAuthorID *uuid.UUID  `json:"post_author_id"`
	Revision     int64       `json:"revision"`
	Title        pgtype.Text `json:"title"`
	Body         string      `json:"body"`
	DisplayName  string      `json:"display_name"`
}

type SocialModerationCase struct {
	ID            uuid.UUID          `json:"id"`
	PostID        *uuid.UUID         `json:"post_id"`
	CommentID     *uuid.UUID         `json:"comment_id"`
	MediaID       *uuid.UUID         `json:"media_id"`
	ProfileID     *uuid.UUID         `json:"profile_id"`
	TargetVersion int64              `json:"target_version"`
	ReporterRef   *uuid.UUID         `json:"reporter_ref"`
	ReasonCode    string             `json:"reason_code"`
	Grounds       string             `json:"grounds"`
	State         string             `json:"state"`
	Version       int64              `json:"version"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type SocialPost struct {
	ID                uuid.UUID          `json:"id"`
	AuthorID          *uuid.UUID         `json:"author_id"`
	CommunityID       *uuid.UUID         `json:"community_id"`
	Kind              string             `json:"kind"`
	State             string             `json:"state"`
	SourcePostID      *uuid.UUID         `json:"source_post_id"`
	ReceiptID         *uuid.UUID         `json:"receipt_id"`
	CurrentRevision   int32              `json:"current_revision"`
	PublishedRevision pgtype.Int4        `json:"published_revision"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	PublishedAt       pgtype.Timestamptz `json:"published_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	Version           int64              `json:"version"`
}

type SocialSelectedResponse struct {
	PostID          uuid.UUID          `json:"post_id"`
	CommentID       uuid.UUID          `json:"comment_id"`
	SelectedBy      uuid.UUID          `json:"selected_by"`
	SelectedAt      pgtype.Timestamptz `json:"selected_at"`
	PostRevision    int32              `json:"post_revision"`
	CommentRevision int64              `json:"comment_revision"`
}
