// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: contracts/proto/recommendation/v1/recommendation.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Candidate struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Revision          int32                  `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty"`
	AuthorId          string                 `protobuf:"bytes,3,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	DedupKey          string                 `protobuf:"bytes,4,opt,name=dedup_key,json=dedupKey,proto3" json:"dedup_key,omitempty"`
	ExplicitInterest  float64                `protobuf:"fixed64,5,opt,name=explicit_interest,json=explicitInterest,proto3" json:"explicit_interest,omitempty"`
	Locality          float64                `protobuf:"fixed64,6,opt,name=locality,proto3" json:"locality,omitempty"`
	Relationship      float64                `protobuf:"fixed64,7,opt,name=relationship,proto3" json:"relationship,omitempty"`
	Freshness         float64                `protobuf:"fixed64,8,opt,name=freshness,proto3" json:"freshness,omitempty"`
	BoundedUsefulness float64                `protobuf:"fixed64,9,opt,name=bounded_usefulness,json=boundedUsefulness,proto3" json:"bounded_usefulness,omitempty"`
	ConversationKey   string                 `protobuf:"bytes,10,opt,name=conversation_key,json=conversationKey,proto3" json:"conversation_key,omitempty"` // canonical published root; empty for older clients
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Candidate) Reset() {
	*x = Candidate{}
	mi := &file_contracts_proto_recommendation_v1_recommendation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Candidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Candidate) ProtoMessage() {}

func (x *Candidate) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_proto_recommendation_v1_recommendation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Candidate.ProtoReflect.Descriptor instead.
func (*Candidate) Descriptor() ([]byte, []int) {
	return file_contracts_proto_recommendation_v1_recommendation_proto_rawDescGZIP(), []int{0}
}

func (x *Candidate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Candidate) GetRevision() int32 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *Candidate) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *Candidate) GetDedupKey() string {
	if x != nil {
		return x.DedupKey
	}
	return ""
}

func (x *Candidate) GetExplicitInterest() float64 {
	if x != nil {
		return x.ExplicitInterest
	}
	return 0
}

func (x *Candidate) GetLocality() float64 {
	if x != nil {
		return x.Locality
	}
	return 0
}

func (x *Candidate) GetRelationship() float64 {
	if x != nil {
		return x.Relationship
	}
	return 0
}

func (x *Candidate) GetFreshness() float64 {
	if x != nil {
		return x.Freshness
	}
	return 0
}

func (x *Candidate) GetBoundedUsefulness() float64 {
	if x != nil {
		return x.BoundedUsefulness
	}
	return 0
}

func (x *Candidate) GetConversationKey() string {
	if x != nil {
		return x.ConversationKey
	}
	return ""
}

type RecommendRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ViewerContext  string                 `protobuf:"bytes,1,opt,name=viewer_context,json=viewerContext,proto3" json:"viewer_context,omitempty"` // request-scoped pseudonym, not an identity-vault ID
	Generation     int64                  `protobuf:"varint,2,opt,name=generation,proto3" json:"generation,omitempty"`
	Surface        string                 `protobuf:"bytes,3,opt,name=surface,proto3" json:"surface,omitempty"`
	Languages      []string               `protobuf:"bytes,4,rep,name=languages,proto3" json:"languages,omitempty"`
	Locality       string                 `protobuf:"bytes,5,opt,name=locality,proto3" json:"locality,omitempty"`
	SnapshotId     string                 `protobuf:"bytes,6,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	DeadlineUnixMs int64                  `protobuf:"varint,7,opt,name=deadline_unix_ms,json=deadlineUnixMs,proto3" json:"deadline_unix_ms,omitempty"`
	Candidates     []*Candidate           `protobuf:"bytes,8,rep,name=candidates,proto3" json:"candidates,omitempty"`
	Limit          uint32                 `protobuf:"varint,9,opt,name=limit,proto3" json:"limit,omitempty"` // <=200; page composition remains authoritative in Go
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RecommendRequest) Reset() {
	*x = RecommendRequest{}
	mi := &file_contracts_proto_recommendation_v1_recommendation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendRequest) ProtoMessage() {}

func (x *RecommendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_proto_recommendation_v1_recommendation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendRequest.ProtoReflect.Descriptor instead.
func (*RecommendRequest) Descriptor() ([]byte, []int) {
	return file_contracts_proto_recommendation_v1_recommendation_proto_rawDescGZIP(), []int{1}
}

func (x *RecommendRequest) GetViewerContext() string {
	if x != nil {
		return x.ViewerContext
	}
	return ""
}

func (x *RecommendRequest) GetGeneration() int64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *RecommendRequest) GetSurface() string {
	if x != nil {
		return x.Surface
	}
	return ""
}

func (x *RecommendRequest) GetLanguages() []string {
	if x != nil {
		return x.Languages
	}
	return nil
}

func (x *RecommendRequest) GetLocality() string {
	if x != nil {
		return x.Locality
	}
	return ""
}

func (x *RecommendRequest) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

func (x *RecommendRequest) GetDeadlineUnixMs() int64 {
	if x != nil {
		return x.DeadlineUnixMs
	}
	return 0
}

func (x *RecommendRequest) GetCandidates() []*Candidate {
	if x != nil {
		return x.Candidates
	}
	return nil
}

func (x *RecommendRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type RankedReference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Revision      int32                  `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty"`
	Explanation   string                 `protobuf:"bytes,3,opt,name=explanation,proto3" json:"explanation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RankedReference) Reset() {
	*x = RankedReference{}
	mi := &file_contracts_proto_recommendation_v1_recommendation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RankedReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankedReference) ProtoMessage() {}

func (x *RankedReference) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_proto_recommendation_v1_recommendation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankedReference.ProtoReflect.Descriptor instead.
func (*RankedReference) Descriptor() ([]byte, []int) {
	return file_contracts_proto_recommendation_v1_recommendation_proto_rawDescGZIP(), []int{2}
}

func (x *RankedReference) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RankedReference) GetRevision() int32 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *RankedReference) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

type RecommendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*RankedReference     `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	ModelVersion  string                 `protobuf:"bytes,2,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`
	PolicyVersion string                 `protobuf:"bytes,3,opt,name=policy_version,json=policyVersion,proto3" json:"policy_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommendResponse) Reset() {
	*x = RecommendResponse{}
	mi := &file_contracts_proto_recommendation_v1_recommendation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendResponse) ProtoMessage() {}

func (x *RecommendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_proto_recommendation_v1_recommendation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendResponse.ProtoReflect.Descriptor instead.
func (*RecommendResponse) Descriptor() ([]byte, []int) {
	return file_contracts_proto_recommendation_v1_recommendation_proto_rawDescGZIP(), []int{3}
}

func (x *RecommendResponse) GetItems() []*RankedReference {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *RecommendResponse) GetModelVersion() string {
	if x != nil {
		return x.ModelVersion
	}
	return ""
}

func (x *RecommendResponse) GetPolicyVersion() string {
	if x != nil {
		return x.PolicyVersion
	}
	return ""
}

var File_contracts_proto_recommendation_v1_recommendation_proto protoreflect.FileDescriptor

const file_contracts_proto_recommendation_v1_recommendation_proto_rawDesc = "" +
	"\n" +
	"6contracts/proto/recommendation/v1/recommendation.proto\x12\x19jansetu.recommendation.v1\"\xd6\x02\n" +
	"\tCandidate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\x05R\brevision\x12\x1b\n" +
	"\tauthor_id\x18\x03 \x01(\tR\bauthorId\x12\x1b\n" +
	"\tdedup_key\x18\x04 \x01(\tR\bdedupKey\x12+\n" +
	"\x11explicit_interest\x18\x05 \x01(\x01R\x10explicitInterest\x12\x1a\n" +
	"\blocality\x18\x06 \x01(\x01R\blocality\x12\"\n" +
	"\frelationship\x18\a \x01(\x01R\frelationship\x12\x1c\n" +
	"\tfreshness\x18\b \x01(\x01R\tfreshness\x12-\n" +
	"\x12bounded_usefulness\x18\t \x01(\x01R\x11boundedUsefulness\x12)\n" +
	"\x10conversation_key\x18\n" +
	" \x01(\tR\x0fconversationKey\"\xd4\x02\n" +
	"\x10RecommendRequest\x12%\n" +
	"\x0eviewer_context\x18\x01 \x01(\tR\rviewerContext\x12\x1e\n" +
	"\n" +
	"generation\x18\x02 \x01(\x03R\n" +
	"generation\x12\x18\n" +
	"\asurface\x18\x03 \x01(\tR\asurface\x12\x1c\n" +
	"\tlanguages\x18\x04 \x03(\tR\tlanguages\x12\x1a\n" +
	"\blocality\x18\x05 \x01(\tR\blocality\x12\x1f\n" +
	"\vsnapshot_id\x18\x06 \x01(\tR\n" +
	"snapshotId\x12(\n" +
	"\x10deadline_unix_ms\x18\a \x01(\x03R\x0edeadlineUnixMs\x12D\n" +
	"\n" +
	"candidates\x18\b \x03(\v2$.jansetu.recommendation.v1.CandidateR\n" +
	"candidates\x12\x14\n" +
	"\x05limit\x18\t \x01(\rR\x05limit\"_\n" +
	"\x0fRankedReference\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\x05R\brevision\x12 \n" +
	"\vexplanation\x18\x03 \x01(\tR\vexplanation\"\xa1\x01\n" +
	"\x11RecommendResponse\x12@\n" +
	"\x05items\x18\x01 \x03(\v2*.jansetu.recommendation.v1.RankedReferenceR\x05items\x12#\n" +
	"\rmodel_version\x18\x02 \x01(\tR\fmodelVersion\x12%\n" +
	"\x0epolicy_version\x18\x03 \x01(\tR\rpolicyVersion2\x7f\n" +
	"\x15RecommendationService\x12f\n" +
	"\tRecommend\x12+.jansetu.recommendation.v1.RecommendRequest\x1a,.jansetu.recommendation.v1.RecommendResponseBMZKgithub.com/lavkushry/JanSetu-AI/services/backend/internal/recommendation/pbb\x06proto3"

var (
	file_contracts_proto_recommendation_v1_recommendation_proto_rawDescOnce sync.Once
	file_contracts_proto_recommendation_v1_recommendation_proto_rawDescData []byte
)

func file_contracts_proto_recommendation_v1_recommendation_proto_rawDescGZIP() []byte {
	file_contracts_proto_recommendation_v1_recommendation_proto_rawDescOnce.Do(func() {
		file_contracts_proto_recommendation_v1_recommendation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contracts_proto_recommendation_v1_recommendation_proto_rawDesc), len(file_contracts_proto_recommendation_v1_recommendation_proto_rawDesc)))
	})
	return file_contracts_proto_recommendation_v1_recommendation_proto_rawDescData
}

var file_contracts_proto_recommendation_v1_recommendation_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_contracts_proto_recommendation_v1_recommendation_proto_goTypes = []any{
	(*Candidate)(nil),         // 0: jansetu.recommendation.v1.Candidate
	(*RecommendRequest)(nil),  // 1: jansetu.recommendation.v1.RecommendRequest
	(*RankedReference)(nil),   // 2: jansetu.recommendation.v1.RankedReference
	(*RecommendResponse)(nil), // 3: jansetu.recommendation.v1.RecommendResponse
}
var file_contracts_proto_recommendation_v1_recommendation_proto_depIdxs = []int32{
	0, // 0: jansetu.recommendation.v1.RecommendRequest.candidates:type_name -> jansetu.recommendation.v1.Candidate
	2, // 1: jansetu.recommendation.v1.RecommendResponse.items:type_name -> jansetu.recommendation.v1.RankedReference
	1, // 2: jansetu.recommendation.v1.RecommendationService.Recommend:input_type -> jansetu.recommendation.v1.RecommendRequest
	3, // 3: jansetu.recommendation.v1.RecommendationService.Recommend:output_type -> jansetu.recommendation.v1.RecommendResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_contracts_proto_recommendation_v1_recommendation_proto_init() }
func file_contracts_proto_recommendation_v1_recommendation_proto_init() {
	if File_contracts_proto_recommendation_v1_recommendation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contracts_proto_recommendation_v1_recommendation_proto_rawDesc), len(file_contracts_proto_recommendation_v1_recommendation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_contracts_proto_recommendation_v1_recommendation_proto_goTypes,
		DependencyIndexes: file_contracts_proto_recommendation_v1_recommendation_proto_depIdxs,
		MessageInfos:      file_contracts_proto_recommendation_v1_recommendation_proto_msgTypes,
	}.Build()
	File_contracts_proto_recommendation_v1_recommendation_proto = out.File
	file_contracts_proto_recommendation_v1_recommendation_proto_goTypes = nil
	file_contracts_proto_recommendation_v1_recommendation_proto_depIdxs = nil
}
